[package]
name = "quick_cmd"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "qc"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
directories-next = "2.0.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
